server:
  servlet:
    path: "/"
  port: 8088
logging:
  level:
    cn.itcast: debug
    #org.springframework: debug
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/springbootssm?characterEncoding=utf-8
    username: root
    password: 123


mybatis:
  #configuration:
    #map-underscore-to-camel-case: true
  type-aliases-package: cn.itcast.pojo
  #mapper-locations: mapper/*.xml